version: '2'
services:
  web:
    build: .
    command: gunicorn -b 0.0.0.0:5000 --workers=2 wsgi:app
    volumes:
      - .:/app
    links:
      - postgres:postgres
    env_file: .env
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - "5432:5432"
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    links:
      - "web:web"
