version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    command: gunicorn -b 0.0.0.0:5000 --workers=5 wsgi:app
    volumes:
      - .:/app
    links:
      - postgres:postgres
    env_file: .env
  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - "5432:5432"
